Fix ValueErrors with testing arrays
Testing for the truth value of the arrays was producing this error:

> ValueError: The truth value of an array with more than one element is
> ambiguous. Use a.any() or a.all()

Looks like this this error was introduced in recent numpy versions.